### ISSUE TITLE
Valser ratted me previously 

### ISSUE THREAD

**Issue by Zane2b2t** [pineapplebby/mio-latest#4]
Don't run he got my mc login data
My brothers name with the 2nd name (my dad)

**Comment by AnotherNoName** [comment]
https://user-images.githubusercontent.com/65259492/209708266-8be4e679-81f5-4ccd-ad06-af6112b8094a.mp4

**Comment by pineapplebby** [comment]
Check the cheat before running retard essam

**Comment by Zane2b2t** [comment]
> Check the cheat before running retard essam

If u have 3 braincells to link mustafa essam and omar essam you would know that its my dad's name
